apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deploy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-deploy
  template:
    metadata:
      labels:
        app: fe-deploy
    spec:
      containers:
        - name: fe-deploy
          image: dhlclove/fe-deploy:1.0.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fe-deploy-service
spec:
  selector:
    app: fe-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fe-deploy-route
spec:
  parentRefs:
  - name: gateway
    namespace: istio-ingress
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /page/deploy
    backendRefs:
    - name: fe-deploy-service
      port: 80
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
